version: 2
jobs:
  node10:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout:
          path: ~/project
      - run:
          name: 'Install solc'
          command: sudo add-apt-repository ppa:ethereum/ethereum -y && sudo apt-get update && apt-cache showpkg solc && sudo apt-get install solc
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-node10-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-node10-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - node10